[package]
name = "papercut"
version = "0.1.0"
edition = "2021"


[dependencies]
winit = "0.26"
wgpu = "0.13"
env_logger = "0.9"
log = "0.4"
pollster = "0.2"
bytemuck = { version = "1.4", features = ["derive"] }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
